#!/usr/bin/env python3


import sys

import qpdfview_session.parse as parse
import qpdfview_session.session_manager as session_manager
import qpdfview_session.storage_manager as storage_manager


def main():
    """
    Main script.

    Parse arguments and take the action specified by the user.
    """
    parser = parse.prepare_parser()
    args = parser.parse_args()

    storage_manager.prepare_storage_dir()

    if args.list:
        for session in session_manager.list_sessions():
            print(session)
    elif args.save:
        session_manager.save_session(args.save)
        print('Current session is saved as {}'.format(args.save))
    elif args.restore:
        try:
            session_manager.restore_session(args.restore)
            print('{} session is restored'.format(args.restore))
        except ValueError as error:
            print(error)
    elif args.delete:
        try:
            session_manager.delete_session(args.delete)
            print('{} session is deleted'.format(args.delete))
        except ValueError as error:
            print(error)
    elif args.backup:
        session_manager.backup_saved_sessions()
        print('Backups generated for all previously saved sessions')
    elif args.clean:
        try:
            session_manager.clean_session()
            print('Current session is cleaned')
        except ValueError as error:
            print(error)
    else:
        parser.print_help()
        sys.exit(1)


if __name__ == '__main__':
    main()
